GET http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json


{
  "username": "lernantino",
  "email": "lernantino@gmail.com"
}
###
PUT http://localhost:3001/api/users/60b28761c3227e1e7aad9f59 HTTP/1.1
Content-Type: application/json


{
  "username": "ernantino",
  "email": "lernantino@gmail.com"
}
###
DELETE http://localhost:3001/api/users/60b287ecc3227e1e7aad9f5a HTTP/1.1
Content-Type: application/json


{
  "username": "ernantino",
  "email": "lernantino@gmail.com"
}
###
GET http://localhost:3001/api/thoughts HTTP/1.1
Content-Type: application/json
###
###
GET http://localhost:3001/api/thoughts/60b318470381cf747cf1d70d HTTP/1.1
Content-Type: application/json
###
POST http://localhost:3001/api/thoughts/60b3188b0381cf747cf1d711 HTTP/1.1
Content-Type: application/json

{
  "thoughtText": "Hgregserger...",
  "username": "lernaergsergno",
  "userId": "60b3188b0381cf747cf1d711"
}
###
DELETE http://localhost:3001/api/thoughts/60b3188b0381cf747cf1d711/60b319063bb75d840f01ddcc HTTP/1.1
Content-Type: application/json


